FROM FROM_SUBST

COPY dai-VERSION_SUBST-1.ARCH_SUBST.rpm dai-VERSION_SUBST-1.rpm

RUN rpm -i dai-VERSION_SUBST-1.rpm
RUN yum install -y boost-devel java-1.8.0-openjdk

ENTRYPOINT systemctl dai start && tail -f /opt/h2oai/dai/log/dai.out


